### ISSUE TITLE
api documentation

### ISSUE THREAD

**Issue by craftyguy** [piekstra/portlandgeneral-api#3]
hi, I was looking to create something like this myself... and found your project! I'm curious if you found any public documentation for the API? Portland General seems to support hourly usage reporting (at least I can see this when I log in and view the dashboard on their site..), and so I'd like to work towards using this for a Home Assistant integration that can track energy.

**Comment by piekstra** [comment]
@craftyguy hi! 

I did find out how to access their hourly utility usage and cost data, and have some work locally on adding that capability to this library. I got sidetracked with other things but can put in some extra effort towards adding that if you're interested!

**Comment by craftyguy** [comment]
nice, ya I'm interested in that!

**Comment by piekstra** [comment]
@craftyguy I've put up a WIP pull request that can get you started with some local experimentation. I'll be updating the PR when I can to be a full version.

https://github.com/piekstra/portlandgeneral-api/pull/5

**Comment by piekstra** [comment]
The power usage and cost features among others are now available with https://github.com/piekstra/portlandgeneral-api/releases/tag/v1.1.0

**Comment by craftyguy** [comment]
thank you so much! \o/
